services:
  importer:
    build:
      context: ./skodaImporter
      dockerfile: Dockerfile
    container_name: skodaImporter
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-exclude *tmp
    restart: always

    depends_on:
      - mariadb
    ports:
      - 80:80
    networks:
      - mariadb_network
    volumes:
      - .:/app
    secrets:
      - SKODA_USER
      - SKODA_PASS
      - MARIADB_DATABASE
      - MARIADB_USERNAME
      - MARIADB_PASSWORD
      - MARIADB_HOSTNAME

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_USER: skoda
      MARIADB_PASSWORD: skodapass
      MARIADB_DATABASE: skoda
      MARIADB_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./sqldump:/docker-entrypoint-initdb.d
      - .db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mariadb_network

  autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  mariadb_network:
    driver: bridge

secrets:
  SKODA_USER:
    file: ./secrets/SKODA_USER
  SKODA_PASS:
    file: ./secrets/SKODA_PASS
  MARIADB_DATABASE:
    file: ./secrets/MARIADB_DATABASE
  MARIADB_USERNAME:
    file: ./secrets/MARIADB_USERNAME
  MARIADB_PASSWORD:
    file: ./secrets/MARIADB_PASSWORD
  MARIADB_HOSTNAME:
    file: ./secrets/MARIADB_HOSTNAME
