services:
  app:
    build: .
    container_name: skodaImporter
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-exclude *tmp
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/app
    secrets:
      - SKODA_USER
      - SKODA_PASS
      - SKODA_AUTH
      - SKODA_VEHICLE

secrets:
  SKODA_USER:
    file: ./secrets/SKODA_USER
  SKODA_PASS:
    file: ./secrets/SKODA_PASS
  SKODA_VEHICLE:
    file: ./secrets/SKODA_VEHICLE
  SKODA_AUTH:
    file: ./secrets/SKODA_AUTH
