apiVersion: apps/v1
kind: Deployment
metadata:
  name: skodaimporter
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: skodaimporter
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skodachargefinder
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: skodachargefinder
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "750m"
            memory: "768Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skodachargecollector
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: skodachargecollector
        resources:
          requests:
            cpu: "300m"
            memory: "384Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skodaupdatechargeprices
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: skodaupdatechargeprices
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skodachargefrontend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: skodachargefrontend
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "750m"
            memory: "768Mi"
