version: "3"
services:
  importer:
    image: ghcr.io/tn8or/skodaimporter:latest
    restart: always
    hostname: skodaimporter
    environment:
      SKODA_USER: ${SKODA_USER}
      SKODA_PASS: ${SKODA_PASS}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}

  chargefinder:
    image: ghcr.io/tn8or/skodachargefinder:latest
    restart: always
    hostname: skodachargefinder
    environment:
      SKODA_USER: ${SKODA_USER}
      SKODA_PASS: ${SKODA_PASS}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}

  chargecollector:
    image: ghcr.io/tn8or/skodachargecollector:latest
    restart: always
    hostname: skodachargecollector
    environment:
      SKODA_USER: ${SKODA_USER}
      SKODA_PASS: ${SKODA_PASS}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
  updatechargeprices:
    image: ghcr.io/tn8or/skodaupdatechargeprices:latest
    restart: always
    hostname: skodaupdatechargeprices
    environment:
      SKODA_USER: ${SKODA_USER}
      SKODA_PASS: ${SKODA_PASS}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
  skodachargefrontend:
    image: ghcr.io/tn8or/skodachargefrontend:latest
    restart: always
    hostname: skodachargefrontend
    networks:
      - ix-nginx-proxy-manager_default
    environment:
      SKODA_USER: ${SKODA_USER}
      SKODA_PASS: ${SKODA_PASS}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}

networks:
  ix-nginx-proxy-manager_default:
    external: true
