version: "3"
services:
  dataloader:
    image: ghcr.io/tn8or/skoda:main
    restart: always

    secrets:
      - SKODA_USER
      - SKODA_PASS

secrets:
  SKODA_USER:
    external: true
  SKODA_PASS:
    external: true
