version: "3"
services:
  dataloader:
    image: ghcr.io/tn8or/skoda:main
    restart: always
    hostname: skodaimporter

    secrets:
      - SKODA_USER
      - SKODA_PASS

    networks:
      - bridge

secrets:
  SKODA_USER:
    external: true
  SKODA_PASS:
    external: true

networks:
  bridge:
    external: true
