apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-app-config
  labels:
    app.kubernetes.io/part-of: skoda
data:
  MARIADB_DATABASE: skoda
  MARIADB_HOSTNAME: mariadb.skoda.svc.cluster.local
  MARIADB_PORT: "3306"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-app-config
  labels:
    app.kubernetes.io/part-of: skoda
data:
  GRAYLOG_PORT: "12201"
